### ISSUE TITLE
More details on buckets would be welcome

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/astra-control-service#121]
Page: [Manage buckets](https://docs.netapp.com/us-en/astra-control-service/use/manage-buckets.html)

1) Add "S3" (edit: blob, etc.) somewhere in the document to improve searchability

2) Explain if it's possible (or not?) to re-assign or clone buckets from one ACC/ACS front end to another and whether that works across hyperscalers. For example:

> Astra Control Service uses this default bucket for the backups and clones that you create. You can then use the backups to restore and clone apps between clusters.

Can I clone a bucket from hyperscaler A to a bucket at hyperscaler B and use it by ACS instance running there? Or can the clone buckets be accessed only by Astra Control instance that created them? Of course, the reader can find out experimentally, but it's time consuming because it'd require multiple AC instances in different hyperscalers, so it's better to have these details explained

**Comment by netapp-mwallis** [comment]
Hi @scaleoutsean, apologies for the delayed response.  I've opened https://jira.ngage.netapp.com/browse/DOC-3978 to track the improvements you suggested.  Can you expand on your "S3" suggestion? 

For your bucket cloning questions, Here are some answers from product management:
-----
In short, no. A bucket is a construct within a single hyperscaler project and is not intended to be portable. 

You CAN clone a k8s application from one hyperscaler to another or between regions in a single hyperscaler today with ACS.
What you actually have is a bucket in each hyperscaler and the data gets replicated by ACS from one to the other. But that is a single backup within a bucket and not a wholesale clone of the bucket with all of its backups inside.
-----

If this is helpful, I can make the above points more clear in the ACS documentation.

**Comment by scaleoutsean** [comment]
- "S3" - I mean when prospects or users search for requirements or general object storage requirements, I suspect most start with "S3" rather than type "object storage", "object store" and such, so if there's no mention of S3 in the documentation they get 0 search results
- The explanation sounds clear and useful and it'd be nice to have it added in there (that was a question a prospect was trying to get from the documentation)

**Comment by netapp-mwallis** [comment]
- Gotcha - S3 isn't mentioned in the ACS documentation as it's not a supported storage service option for ACS (ACC only).  Have you seen that customers still search on S3 in ACS documentation, to find requirements?  If so, I can add S3 as a keyword in the topic, so that it won't be visible, but still give a hit on search results.
- Understood; I'll add the information to the docs.

**Comment by netapp-mwallis** [comment]
Thanks - I've added S3 and related keywords to that topic, and also added the following info to the buckets introduction:

"You can not clone a bucket from one cloud provider to another cloud provider. To migrate data from one cloud provider to another, clone the associated application instead."

If you approve, I'll make this change public. Thanks!

**Comment by scaleoutsean** [comment]
Looks good to me
