### ISSUE TITLE
Storage classes needs review

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/astra-control-service#123]
Page: [Service type, storage classes, and PV size for GKE clusters](https://docs.netapp.com/us-en/astra-control-service/learn/choose-class-and-size.html)

The storage classes names needs your review.
CVS-Performance storage classes:
netapp-cvs-standard --> netapp-cvs-perf-standard
netapp-cvs-premium --> netapp-cvs-perf-premium
netapp-cvs-extreme --> netapp-cvs-perf-extreme
Note: CVS storage class is correct as it is "netapp-cvs-standard"

Adding a couple of shots for your reference:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/34706481/145194459-7af49caf-949c-4180-a726-990faaf8ee1a.png">
<img width="874" alt="image" src="https://user-images.githubusercontent.com/34706481/145194541-7beb8228-f434-4f49-9da5-ce7a4a851203.png">

**Comment by netapp-mwallis** [comment]
Thanks @gabrieltokyo - and apologies for the delay.  I'll get this fix in and ask you to review the change before it goes public.

**Comment by netapp-mwallis** [comment]
Hi @gabrieltokyo , can you take a look at the below link and let me know if you approve? If so, I'll make this change public.
Thanks!
https://review.docs.netapp.com/us-en/astra-control-service_mw-hotfix-gh-issues/learn/choose-class-and-size.html

**Comment by gabrieltokyo** [comment]
Thank you @netapp-mwallis, you will need to roll back the CVS part.
Changes at CVS-Performance row are correct.
CVS row did not need any change, so you can set it back to netapp-cvs-standard

**Comment by netapp-mwallis** [comment]
Thanks, @gabrieltokyo - I've reversed the change to the standard CVS storage class.  Can you double check at the following link?
https://review.docs.netapp.com/us-en/astra-control-service_mw-hotfix-gh-issues/learn/choose-class-and-size.html

**Comment by netapp-mwallis** [comment]
@gabrieltokyo  I've made this change public, since it was a small change. Please let me know if you see any issues. Thanks!
https://docs.netapp.com/us-en/astra-control-service/learn/choose-class-and-size.html

**Comment by gabrieltokyo** [comment]
Thank you @netapp-mwallis the changes are perfect.

Have a nice time!
