### ISSUE TITLE
Most content is lost in the localized pages

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/astra-control-service#136]
Page: [Deploy Jenkins from a Helm chart](https://docs.netapp.com/us-en/astra-control-service/solutions/jenkins-deploy-from-helm-chart.html)

https://docs.netapp.com/us-en/astra-control-service/solutions/jenkins-deploy-from-helm-chart.html is displayed differently from English version when a language is selected from the language filter.

**Comment by netapp-mwallis** [comment]
Hi @yukakou, 

Thanks for bringing this to our attention.  It looks like the affected topics are ones that are shared between documentation repositories.  I'm asking the IE Tools team if this is a known issue, or if there is something we can do to fix it.  I'll update here when I know more.

Thanks again,
Michael

**Comment by netapp-mwallis** [comment]
Hi @yukakou - the Tools team let me know that this is a known issue with the software used for translation, and that they are working on resolving this.  I'll keep you posted with the progress.

**Comment by netapp-mwallis** [comment]
Hi @yukakou, apologies for the delay in getting back to you with an update.  The IE tools team has resolved this issue.  The content should be displayed correctly now for translated pages that reuse text from other topics.  
Let us know if you see any other issues.  Thanks!
--Michael

**Comment by yukakou** [comment]
Glad to know it solved now! Thank you @netapp-mwallis :) I'll inform it to SEs.
