### ISSUE TITLE
filtered site pdf for azure is broken starting at this page

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/astra-control-service#156]
Page: [Learn about Astra Control](https://docs.netapp.com/us-en/astra-control-service/get-started/intro.html)

The site and L1 node PDFs when filtered for Azure are truncated in this topic, ending here:

![image](https://user-images.githubusercontent.com/56453501/185189680-1109ccd9-d52d-45be-ab9b-bec1c75fdd3b.png)

The actual URL after filtering is https://docs.netapp.com/us-en/astra-control-service/azure/get-started/intro.html#how-astra-control-service-works

And the source is in this section: https://github.com/NetAppDocs/astra-control-service/blob/main/get-started/intro.adoc?plain=1#L71

I haven't checked to see if the topic should or should not end here, but the PDFs are truncated at this point. It's not just that this topic might be incorrectly truncated, it's affecting all subsequent pages within the scope of the PDF. None of them are there, not even the legal boilerplate. 

I have the PDFs if you want them - save you having to get everything yourself.

**Comment by ntap-bmegan** [comment]
@netapp-bcammett thinks that the `ifdef` on line 82 was left open.

**Comment by netapp-mwallis** [comment]
Thanks for catching this @ntap-bmegan and @netapp-bcammett.  Fixed draft is here: 
https://review.docs.netapp.com/us-en/astra-control-service_gh-issue-156-hotfix/get-started/intro.html

**Comment by ntap-bmegan** [comment]
Confirming that the list was truncated, as was the page beyond the list. For comparison:
