### ISSUE TITLE
Adding info on the specific required fields for adding buckets from AWS and Azure

### ISSUE THREAD

**Issue by luisrico** [NetAppDocs/astra-control-service#159]
Page: [Manage buckets](https://docs.netapp.com/us-en/astra-control-service/use/manage-buckets.html)
In "Add an additional bucket" section, we should provide more information on how to fill the required fields in the case of:
- AWS: Explain what we are asking when the user has to fill "S3 server name or PI address", that is: the S3 endpoint depending of the region of the bucket specified in here: https://docs.aws.amazon.com/general/latest/gr/s3.html, without the https://. As example, "s3.us-east-2.amazonaws.com" if the bucket is in the us-east-2 region.
- Azure: explain how to fill the "Storage account" field, and remind users that storage account containing the container (S3 bucket) has to be created under the a resource group called "astra-backup-rg"

**Comment by netapp-mwallis** [comment]
Hi @luisrico, thanks for bringing these issues to our attention.  I'll work on this and reach out with any questions.
