### ISSUE TITLE
ERROR in FAQ# Can Astra Control manage an application that is on non-NetApp storage?

### ISSUE THREAD

**Issue by victorfrancoramos** [NetAppDocs/astra-control-service#160]
Page: [Frequently asked questions for Astra Control Service](https://docs.netapp.com/us-en/astra-control-service/get-started/faq.html)
It says that "No. While Astra Control can discover applications that are using non-NetApp storage, it can’t manage an application that’s using non-NetApp storage. "
While in other part of the documentation we get that (But at the same time... https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html#configure-container-storage-interface-csi-driver-details-2 ):
"Configure Container Storage Interface (CSI) driver details
To use Azure managed disks with Astra Control Service, you’ll first need to configure CSI volume snapshot capability for Kubernetes versions older than 1.21 and also install the required CSI drivers. "

**Comment by netapp-mwallis** [comment]
Hi @victorfrancoramos, thanks for bringing this to our attention.  We'll get this FAQ updated with the correct information and update here when complete.

**Comment by netapp-mwallis** [comment]
Hi @victorfrancoramos, I've updated the documentation by removing this FAQ entry since it no longer applies to the current state of Astra Control Service.  Thanks again for pointing this out.  I'll close this issue.
