### ISSUE TITLE
Azure Disk Storage vs Azure Managed Disk

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/astra-control-service#166]
Page: [Learn about Astra Control](https://docs.netapp.com/us-en/astra-control-service/get-started/intro.html)

We have the line:
For AKS clusters, Astra Control Service uses [Azure NetApp Files](https://cloud.netapp.com/azure-netapp-files) or Azure Disk Storage as the storage backend for your persistent volumes.

Later (https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html)  the docs are referring to Azure Managed Disk and not Azure Disk Storage. Both terms are valid but we should keep consistent. As Azure Managed Disk is the more used term, we should go for Azure Managed Disk

**Comment by amgrissino** [comment]
Hello - thank you for bringing this to our attention. We will check with some folks and update the content. Thanks for the feedback!

**Comment by netapp-mwallis** [comment]
Hi @ntap-johanneswagner, just a heads up that I've committed the fix for this wording issue. Thanks again for bringing this to our attention.
Take care,
Michael
