### ISSUE TITLE
outdated information needs correcting...

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/astra-control-service#171]
Page: [Frequently asked questions for Astra Control Service](https://docs.netapp.com/us-en/astra-control-service/get-started/faq.html)

The image type of "ubuntu" is no longer supported in GKE.  I have tested ACS with a gke image type of "COS_CONTAINERD" and it appears to work without issue.  Please verify with the product team that this new image type is supported and update the doc.  thanks!

**Comment by mdmiller99** [comment]
Confirmed that COS_CONTAINERD is the default and supported image type to use with GKE and ACS (via Kevin Lambright)

**Comment by netapp-mwallis** [comment]
Hi @mdmiller99, thanks for this feedback.  We'll get this corrected in the documentation and reach out if any questions.
Thanks, 
Michael

**Comment by mdmiller99** [comment]
I'm realizing the references to running ACS on an ubuntu image in GKE are on many different docs.netapp pages. Please review and update all the ACS on GKE pages and replace "ubuntu" with "COS_CONTAINERD" for the supported image type. GCP no longer allows "ubuntu" image type when creating a GKE cluster.

thanks again,

matt

**Comment by netapp-mwallis** [comment]
This info has been corrected and will ship with the next release.  Thanks, @mdmiller99!

--Michael
