### ISSUE TITLE
CVO missing

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/astra-control-service#185]
Page: [Learn about Astra Control](https://docs.netapp.com/us-en/astra-control-service/get-started/intro.html)

What is the storage backend support?: CVO support was introduced in the last release, this is missing in this docs page for astra control service

**Comment by netapp-mwallis** [comment]
Hi @ntap-johanneswagner , thanks for reaching out about this issue.  I'll reach out to you with more details on the progress of this doc improvement.

**Comment by netapp-mwallis** [comment]
This issue has now been fixed; NetApp Cloud Volumes is now listed as a supported storage backend option for Astra Control Service.  Thanks @ntap-johanneswagner.
