### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/astra-control-service#190]
Page: [Start managing Kubernetes clusters from Astra Control Service](https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html)

the following link on this page is broken:  https://docs.netapp.com/us-en/astra-control-service/get-started/requirements.html#operational-environment-requirements

please update.  thanks!

**Comment by netapp-mwallis** [comment]
Hi @mdmiller99, many thanks for letting us know about this.  I'll fix ASAP.  
Thanks,
Michael
