### ISSUE TITLE
extra step needed?

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/astra-control-service#207]
Page: [Set up Amazon Web Services](https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-amazon-web-services.html)

In the section on "install an external snapshotter", step 2, it indicates that the YAML manifests should be modified; however, the code block has kubectl commands that will directly download and install the CRDs.  I haven't opened up these CRDs to see what might need to be modified, but the steps provided don't allow for an intermediate step to make the modifications.

**Comment by netapp-mwallis** [comment]
Thanks @mdmiller99 - we're taking a look at this now.  Thank you for letting us know about this issue.

**Comment by netapp-mwallis** [comment]
I've opened https://jira.ngage.netapp.com/browse/ASTRADOC-169 to track this issue.

**Comment by netapp-mwallis** [comment]
The [ACS documentation](https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-amazon-web-services.html#eks-cluster-requirements) has been changed to refer users to the Trident documentation for the snapshot controller installation, so the Trident documentation is being modified to accommodate this improvement:

https://github.com/NetAppDocs/trident-internal/pull/258

**Comment by netapp-mwallis** [comment]
Trident documentation fix has been merged.  @mdmiller99  Let me know if you see any issues with this fix.

https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller
