### ISSUE TITLE
Links are mistaken

### ISSUE THREAD

**Issue by seijitanabe** [NetAppDocs/astra-control-service#232]
### Page URL

https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html

### Page title

What's new with Astra Control Service

### Summary

Hi Team,

I found some mistaken links in the section "7 November 2023" of this page.

1. **Immutable backups** - "unalterable, read-only backups" is linked to the 404 error page.
2. **Astra Control Service support for on-premises Red Hat OpenShift Container Platform clusters** - "Add a cluster" is linked to "Restore apps" page. (I think it is incorrect.)
3. **Astra Control Service support for Red Hat OpenShift Service on AWS (ROSA) clusters** - "Add a cluster" is the same as above.

Thanks,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Thank you @seijitanabe for your feedback - we will fix these issues as soon as possible.

**Comment by netapp-mwallis** [comment]
This issue has been fixed. Thank you, @seijitanabe!
