### ISSUE TITLE
Docs are not clear on cloud-bridge-url format

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/astra-control-service#242]
### Page URL

https://docs.netapp.com/us-en/astra-control-service/get-started/install-astra-connector.html

### Page title

Install Astra Connector for private clusters

### Summary

Deploying the connector only works if the cloud-bridge-url value has a leading "https://". Otherwise the connector setup will fail with "unsupported protocol scheme". This is not very clear from the documentation. I suggest an example is given (which should match the typical customer setup). Can we change point 5 of "Install Astra Connector" to:

<ASTRA_CONTROL_SERVICE_URL>: The web UI URL of Astra Control Service. For Example: "https://astra.netapp.io" 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @wonderland, thanks for submitting this issue.  We will address this as soon as possible.

**Comment by netapp-mwallis** [comment]
The example has been improved - this doc improvement is now live.
https://docs.netapp.com/us-en/astra-control-service/get-started/install-astra-connector.html
