### ISSUE TITLE
Supported backend list not accurate

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-service#251]
### Page URL

https://docs.netapp.com/us-en/astra-control-service/get-started/intro.html

### Page title

Learn about Astra Control

### Summary

Hi,
the list of backends supported by ACS on the ACC page does not include Longhorn.
however, Longhorn appears on the ACC page:
https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#storage-backends
++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Thanks for catching this @YvosOnTheHub - we'll fix as soon as possible and update when complete.

**Comment by netapp-mwallis** [comment]
This issue has been resolved with ASTRADOC-429.
